# Generated by Django 5.0.2 on 2025-03-11 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_data', '0001_initial'),
        ('users', '0004_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcalculatedrecord',
            name='input_record',
        ),
        migrations.CreateModel(
            name='PlantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('truck_no', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('party_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mv', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('oil', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('starch', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maize_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dm', models.DecimalField(decimal_places=2, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rate_on_dm', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('oil_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('net_wo_oil_fiber', models.DecimalField(decimal_places=2, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('starch_per_point', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('starch_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('grain', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('doc', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_records', to='users.plant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomColumn',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
        migrations.DeleteModel(
            name='PlantCalculatedRecord',
        ),
        migrations.DeleteModel(
            name='PlantInputRecord',
        ),
        migrations.AddIndex(
            model_name='plantrecord',
            index=models.Index(fields=['date'], name='plant_data__date_b31fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='plantrecord',
            index=models.Index(fields=['code'], name='plant_data__code_93a174_idx'),
        ),
        migrations.AddIndex(
            model_name='plantrecord',
            index=models.Index(fields=['product'], name='plant_data__product_dcd0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='plantrecord',
            index=models.Index(fields=['party_name'], name='plant_data__party_n_2ad672_idx'),
        ),
    ]
