# Generated by Django 5.0.2 on 2025-03-13 15:32

from django.db import migrations
from decimal import Decimal

def create_default_variables(apps, schema_editor):
    """Create default formula variables for calculations"""
    FormulaVariable = apps.get_model('plant_data', 'FormulaVariable')
    
    # Define default variables
    default_variables = [
        {
            'name': 'dm_factor',
            'display_name': 'DM Factor',
            'description': 'Factor used in DM calculation: DM = DM Factor - MV',
            'value': Decimal('100'),
            'default_value': Decimal('100')
        },
        {
            'name': 'oil_value_factor',
            'display_name': 'Oil Value Factor',
            'description': 'Factor used in Oil Value calculation: Oil Value = Oil Value Factor * Oil',
            'value': Decimal('60'),
            'default_value': Decimal('60')
        },
        {
            'name': 'net_factor',
            'display_name': 'Net Factor',
            'description': 'Factor used in Net calculation: Net = Net Factor - Oil - Fiber',
            'value': Decimal('100'),
            'default_value': Decimal('100')
        },
        {
            'name': 'starch_per_point_divisor',
            'display_name': 'Starch Per Point Divisor',
            'description': 'Divisor used in Starch Per Point calculation: Starch Per Point = Maize Rate / Divisor',
            'value': Decimal('64'),
            'default_value': Decimal('64')
        },
        {
            'name': 'grain_factor',
            'display_name': 'Grain Factor',
            'description': 'Factor used in Grain calculation: Grain = Starch * Grain Factor',
            'value': Decimal('0.70'),
            'default_value': Decimal('0.70')
        },
    ]
    
    # Create each variable
    for var_data in default_variables:
        FormulaVariable.objects.create(**var_data)

def remove_variables(apps, schema_editor):
    """Remove all formula variables (reverse migration)"""
    FormulaVariable = apps.get_model('plant_data', 'FormulaVariable')
    FormulaVariable.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('plant_data', '0003_formulavariable'),
    ]

    operations = [
        migrations.RunPython(
            create_default_variables,
            reverse_code=remove_variables
        ),
    ]
