"""initial_migration

Revision ID: 2ae2c0123252
Revises: 
Create Date: 2025-04-03 11:01:32.036903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae2c0123252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('default_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_variables_id'), 'formula_variables', ['id'], unique=False)
    op.create_index(op.f('ix_formula_variables_name'), 'formula_variables', ['name'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_name'), 'plants', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='rolecategoryenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('plant_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('truck_no', sa.String(length=50), nullable=True),
    sa.Column('bill_no', sa.String(length=50), nullable=True),
    sa.Column('party_name', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('oil', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fiber', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starch', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maize_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_on_dm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('oil_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_wo_oil_fiber', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starch_per_point', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starch_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grain', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('doc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_records_code'), 'plant_records', ['code'], unique=False)
    op.create_index(op.f('ix_plant_records_date'), 'plant_records', ['date'], unique=False)
    op.create_index(op.f('ix_plant_records_id'), 'plant_records', ['id'], unique=False)
    op.create_index(op.f('ix_plant_records_plant_id'), 'plant_records', ['plant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('has_changed_password', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'PROFILE_UPDATE', 'DATA_CREATION', 'DATA_UPDATE', 'DATA_DELETION', 'SYSTEM_ACTION', name='actiontypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plant_records_plant_id'), table_name='plant_records')
    op.drop_index(op.f('ix_plant_records_id'), table_name='plant_records')
    op.drop_index(op.f('ix_plant_records_date'), table_name='plant_records')
    op.drop_index(op.f('ix_plant_records_code'), table_name='plant_records')
    op.drop_table('plant_records')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plants_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_formula_variables_name'), table_name='formula_variables')
    op.drop_index(op.f('ix_formula_variables_id'), table_name='formula_variables')
    op.drop_table('formula_variables')
    # ### end Alembic commands ###
