"""add reset_token to users table

Revision ID: 8154347aa8af
Revises: 9f40f4a0cae6
Create Date: 2025-04-02 15:53:32.963365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8154347aa8af'
down_revision: Union[str, None] = '9f40f4a0cae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
