"""Add display_name column to formula_variables table

Revision ID: 9f40f4a0cae6
Revises: 
Create Date: 2025-04-02 15:22:10.269268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = '9f40f4a0cae6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add display_name column as nullable first
    op.add_column('formula_variables', sa.Column('display_name', sa.String(length=100), nullable=True))
    
    # Create a table object for the update
    formula_variables = table('formula_variables',
        column('name', sa.String),
        column('display_name', sa.String)
    )
    
    # Update existing records to use name as display_name
    op.execute(
        formula_variables.update().values(
            display_name=formula_variables.c.name
        )
    )
    
    # Now make the column non-nullable
    op.alter_column('formula_variables', 'display_name',
                    existing_type=sa.String(length=100),
                    nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula_variables', 'display_name')
    # ### end Alembic commands ###
